// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PatientDataService.proto

package joanna.CA1.Smarthealth;

public interface GetPrescriptionInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Smarthealth.GetPrescriptionInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string patientID = 1;</code>
   * @return The patientID.
   */
  java.lang.String getPatientID();
  /**
   * <code>string patientID = 1;</code>
   * @return The bytes for patientID.
   */
  com.google.protobuf.ByteString
      getPatientIDBytes();
}
