// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PatientDataService.proto

package joanna.CA1.Smarthealth;

public interface LabResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Smarthealth.LabResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string doctorID = 1;</code>
   * @return The doctorID.
   */
  java.lang.String getDoctorID();
  /**
   * <code>string doctorID = 1;</code>
   * @return The bytes for doctorID.
   */
  com.google.protobuf.ByteString
      getDoctorIDBytes();

  /**
   * <code>string patientID = 2;</code>
   * @return The patientID.
   */
  java.lang.String getPatientID();
  /**
   * <code>string patientID = 2;</code>
   * @return The bytes for patientID.
   */
  com.google.protobuf.ByteString
      getPatientIDBytes();

  /**
   * <code>.google.protobuf.Timestamp date = 3;</code>
   * @return Whether the date field is set.
   */
  boolean hasDate();
  /**
   * <code>.google.protobuf.Timestamp date = 3;</code>
   * @return The date.
   */
  com.google.protobuf.Timestamp getDate();
  /**
   * <code>.google.protobuf.Timestamp date = 3;</code>
   */
  com.google.protobuf.TimestampOrBuilder getDateOrBuilder();

  /**
   * <code>string labType = 4;</code>
   * @return The labType.
   */
  java.lang.String getLabType();
  /**
   * <code>string labType = 4;</code>
   * @return The bytes for labType.
   */
  com.google.protobuf.ByteString
      getLabTypeBytes();

  /**
   * <code>string results = 5;</code>
   * @return The results.
   */
  java.lang.String getResults();
  /**
   * <code>string results = 5;</code>
   * @return The bytes for results.
   */
  com.google.protobuf.ByteString
      getResultsBytes();

  /**
   * <code>string diagnosis = 6;</code>
   * @return The diagnosis.
   */
  java.lang.String getDiagnosis();
  /**
   * <code>string diagnosis = 6;</code>
   * @return The bytes for diagnosis.
   */
  com.google.protobuf.ByteString
      getDiagnosisBytes();
}
