// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PermissionService.proto

package joanna.CA1.Smarthealth;

public final class PermissionServiceImplBase {
  private PermissionServiceImplBase() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Smarthealth_AccessInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Smarthealth_AccessInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Smarthealth_RequestLogHistoryInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Smarthealth_RequestLogHistoryInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Smarthealth_AccessLogEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Smarthealth_AccessLogEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027PermissionService.proto\022\013Smarthealth\032\037" +
      "google/protobuf/timestamp.proto\032\014Shared." +
      "proto\"1\n\nAccessInfo\022\020\n\010doctorID\030\001 \001(\t\022\021\n" +
      "\tpatientID\030\002 \001(\t\"<\n\025RequestLogHistoryInf" +
      "o\022\020\n\010doctorID\030\001 \001(\t\022\021\n\tpatientID\030\002 \001(\t\"e" +
      "\n\016AccessLogEntry\022(\n\004date\030\001 \001(\0132\032.google." +
      "protobuf.Timestamp\022\022\n\naccessType\030\002 \001(\t\022\025" +
      "\n\roperationType\030\003 \001(\t2\377\001\n\021PermissionServ" +
      "ice\022G\n\016GiveDataAccess\022\027.Smarthealth.Acce" +
      "ssInfo\032\032.Smarthealth.RequestResult\"\000\022H\n\017" +
      "RemoveDataAcess\022\027.Smarthealth.AccessInfo" +
      "\032\032.Smarthealth.RequestResult\"\000\022W\n\020GetAcc" +
      "essHistory\022\".Smarthealth.RequestLogHisto" +
      "ryInfo\032\033.Smarthealth.AccessLogEntry\"\0000\001B" +
      "5\n\026joanna.CA1.SmarthealthB\031PermissionSer" +
      "viceImplBaseP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
          joanna.CA1.Smarthealth.Shared.getDescriptor(),
        });
    internal_static_Smarthealth_AccessInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Smarthealth_AccessInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Smarthealth_AccessInfo_descriptor,
        new java.lang.String[] { "DoctorID", "PatientID", });
    internal_static_Smarthealth_RequestLogHistoryInfo_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Smarthealth_RequestLogHistoryInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Smarthealth_RequestLogHistoryInfo_descriptor,
        new java.lang.String[] { "DoctorID", "PatientID", });
    internal_static_Smarthealth_AccessLogEntry_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Smarthealth_AccessLogEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Smarthealth_AccessLogEntry_descriptor,
        new java.lang.String[] { "Date", "AccessType", "OperationType", });
    com.google.protobuf.TimestampProto.getDescriptor();
    joanna.CA1.Smarthealth.Shared.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
