// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PatientDataService.proto

package joanna.CA1.Smarthealth;

public interface PrescriptionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Smarthealth.Prescription)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string doctorID = 1;</code>
   * @return The doctorID.
   */
  java.lang.String getDoctorID();
  /**
   * <code>string doctorID = 1;</code>
   * @return The bytes for doctorID.
   */
  com.google.protobuf.ByteString
      getDoctorIDBytes();

  /**
   * <code>string patientID = 2;</code>
   * @return The patientID.
   */
  java.lang.String getPatientID();
  /**
   * <code>string patientID = 2;</code>
   * @return The bytes for patientID.
   */
  com.google.protobuf.ByteString
      getPatientIDBytes();

  /**
   * <code>.google.protobuf.Timestamp date = 3;</code>
   * @return Whether the date field is set.
   */
  boolean hasDate();
  /**
   * <code>.google.protobuf.Timestamp date = 3;</code>
   * @return The date.
   */
  com.google.protobuf.Timestamp getDate();
  /**
   * <code>.google.protobuf.Timestamp date = 3;</code>
   */
  com.google.protobuf.TimestampOrBuilder getDateOrBuilder();

  /**
   * <code>string prescriptionText = 4;</code>
   * @return The prescriptionText.
   */
  java.lang.String getPrescriptionText();
  /**
   * <code>string prescriptionText = 4;</code>
   * @return The bytes for prescriptionText.
   */
  com.google.protobuf.ByteString
      getPrescriptionTextBytes();
}
