// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SupportService.proto

package joanna.CA1.Smarthealth;

public interface QueueStatusInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Smarthealth.QueueStatusInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string userID = 1;</code>
   * @return The userID.
   */
  java.lang.String getUserID();
  /**
   * <code>string userID = 1;</code>
   * @return The bytes for userID.
   */
  com.google.protobuf.ByteString
      getUserIDBytes();

  /**
   * <code>int32 rankInQueue = 2;</code>
   * @return The rankInQueue.
   */
  int getRankInQueue();
}
