// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Shared.proto

package joanna.CA1.Smarthealth;

public interface RequestResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Smarthealth.RequestResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool success = 1;</code>
   * @return The success.
   */
  boolean getSuccess();

  /**
   * <pre>
   * if 'success' is false, then this field may contain additional information
   * </pre>
   *
   * <code>string nonSuccessHint = 2;</code>
   * @return The nonSuccessHint.
   */
  java.lang.String getNonSuccessHint();
  /**
   * <pre>
   * if 'success' is false, then this field may contain additional information
   * </pre>
   *
   * <code>string nonSuccessHint = 2;</code>
   * @return The bytes for nonSuccessHint.
   */
  com.google.protobuf.ByteString
      getNonSuccessHintBytes();
}
