// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SupportService.proto

package joanna.CA1.Smarthealth;

public interface RequestChatInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Smarthealth.RequestChatInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string userID = 1;</code>
   * @return The userID.
   */
  java.lang.String getUserID();
  /**
   * <code>string userID = 1;</code>
   * @return The bytes for userID.
   */
  com.google.protobuf.ByteString
      getUserIDBytes();

  /**
   * <code>string subject = 2;</code>
   * @return The subject.
   */
  java.lang.String getSubject();
  /**
   * <code>string subject = 2;</code>
   * @return The bytes for subject.
   */
  com.google.protobuf.ByteString
      getSubjectBytes();

  /**
   * <code>string description = 3;</code>
   * @return The description.
   */
  java.lang.String getDescription();
  /**
   * <code>string description = 3;</code>
   * @return The bytes for description.
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();

  /**
   * <code>string phoneNumber = 4;</code>
   * @return The phoneNumber.
   */
  java.lang.String getPhoneNumber();
  /**
   * <code>string phoneNumber = 4;</code>
   * @return The bytes for phoneNumber.
   */
  com.google.protobuf.ByteString
      getPhoneNumberBytes();

  /**
   * <code>string preferredTime = 5;</code>
   * @return The preferredTime.
   */
  java.lang.String getPreferredTime();
  /**
   * <code>string preferredTime = 5;</code>
   * @return The bytes for preferredTime.
   */
  com.google.protobuf.ByteString
      getPreferredTimeBytes();
}
