// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PatientDataService.proto

package grpc.Joanna.PatientDataService;

public interface GetPrescriptionInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetPrescriptionInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string patientID = 1;</code>
   */
  java.lang.String getPatientID();
  /**
   * <code>string patientID = 1;</code>
   */
  com.google.protobuf.ByteString
      getPatientIDBytes();
}
