// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PatientDataService.proto

package grpc.Joanna.PatientDataService;

public interface LabResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:LabResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string doctorID = 1;</code>
   */
  java.lang.String getDoctorID();
  /**
   * <code>string doctorID = 1;</code>
   */
  com.google.protobuf.ByteString
      getDoctorIDBytes();

  /**
   * <code>string patientID = 2;</code>
   */
  java.lang.String getPatientID();
  /**
   * <code>string patientID = 2;</code>
   */
  com.google.protobuf.ByteString
      getPatientIDBytes();

  /**
   * <code>.google.protobuf.Timestamp date = 3;</code>
   */
  boolean hasDate();
  /**
   * <code>.google.protobuf.Timestamp date = 3;</code>
   */
  com.google.protobuf.Timestamp getDate();
  /**
   * <code>.google.protobuf.Timestamp date = 3;</code>
   */
  com.google.protobuf.TimestampOrBuilder getDateOrBuilder();

  /**
   * <code>string labType = 4;</code>
   */
  java.lang.String getLabType();
  /**
   * <code>string labType = 4;</code>
   */
  com.google.protobuf.ByteString
      getLabTypeBytes();

  /**
   * <code>string results = 5;</code>
   */
  java.lang.String getResults();
  /**
   * <code>string results = 5;</code>
   */
  com.google.protobuf.ByteString
      getResultsBytes();

  /**
   * <code>string diagnosis = 6;</code>
   */
  java.lang.String getDiagnosis();
  /**
   * <code>string diagnosis = 6;</code>
   */
  com.google.protobuf.ByteString
      getDiagnosisBytes();
}
