// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PatientDataService.proto

package grpc.Joanna.PatientDataService;

public final class PatientDataServiceImpl {
  private PatientDataServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Prescription_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Prescription_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LabResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LabResult_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetPrescriptionInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetPrescriptionInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DoctorNote_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DoctorNote_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RequestResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RequestResult_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030PatientDataService.proto\032\037google/proto" +
      "buf/timestamp.proto\"w\n\014Prescription\022\020\n\010d" +
      "octorID\030\001 \001(\t\022\021\n\tpatientID\030\002 \001(\t\022(\n\004date" +
      "\030\003 \001(\0132\032.google.protobuf.Timestamp\022\030\n\020pr" +
      "escriptionText\030\004 \001(\t\"\217\001\n\tLabResult\022\020\n\010do" +
      "ctorID\030\001 \001(\t\022\021\n\tpatientID\030\002 \001(\t\022(\n\004date\030" +
      "\003 \001(\0132\032.google.protobuf.Timestamp\022\017\n\007lab" +
      "Type\030\004 \001(\t\022\017\n\007results\030\005 \001(\t\022\021\n\tdiagnosis" +
      "\030\006 \001(\t\"(\n\023GetPrescriptionInfo\022\021\n\tpatient" +
      "ID\030\001 \001(\t\"\226\001\n\nDoctorNote\022\020\n\010doctorID\030\001 \001(" +
      "\t\022\021\n\tpatientID\030\002 \001(\t\022(\n\004date\030\003 \001(\0132\032.goo" +
      "gle.protobuf.Timestamp\022\021\n\tdiagnosis\030\004 \001(" +
      "\t\022\027\n\017recommendations\030\005 \001(\t\022\r\n\005notes\030\006 \001(" +
      "\t\"8\n\rRequestResult\022\017\n\007success\030\001 \001(\010\022\026\n\016n" +
      "onSuccessHint\030\002 \001(\t2\347\001\n\022PatientDataServi" +
      "ce\0222\n\017AddPrescription\022\r.Prescription\032\016.R" +
      "equestResult\"\000\022;\n\020GetPrescriptions\022\024.Get" +
      "PrescriptionInfo\032\r.Prescription\"\0000\001\022/\n\rA" +
      "ddLabResults\022\n.LabResult\032\016.RequestResult" +
      "\"\000(\001\022/\n\016AddDoctorNotes\022\013.DoctorNote\032\016.Re" +
      "questResult\"\000B:\n\036grpc.Joanna.PatientData" +
      "ServiceB\026PatientDataServiceImplP\001b\006proto" +
      "3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        }, assigner);
    internal_static_Prescription_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Prescription_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Prescription_descriptor,
        new java.lang.String[] { "DoctorID", "PatientID", "Date", "PrescriptionText", });
    internal_static_LabResult_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_LabResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LabResult_descriptor,
        new java.lang.String[] { "DoctorID", "PatientID", "Date", "LabType", "Results", "Diagnosis", });
    internal_static_GetPrescriptionInfo_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_GetPrescriptionInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetPrescriptionInfo_descriptor,
        new java.lang.String[] { "PatientID", });
    internal_static_DoctorNote_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_DoctorNote_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DoctorNote_descriptor,
        new java.lang.String[] { "DoctorID", "PatientID", "Date", "Diagnosis", "Recommendations", "Notes", });
    internal_static_RequestResult_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_RequestResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RequestResult_descriptor,
        new java.lang.String[] { "Success", "NonSuccessHint", });
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
