// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PatientDataService.proto

package grpc.Joanna.PatientDataService;

public interface PrescriptionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Prescription)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string doctorID = 1;</code>
   */
  java.lang.String getDoctorID();
  /**
   * <code>string doctorID = 1;</code>
   */
  com.google.protobuf.ByteString
      getDoctorIDBytes();

  /**
   * <code>string patientID = 2;</code>
   */
  java.lang.String getPatientID();
  /**
   * <code>string patientID = 2;</code>
   */
  com.google.protobuf.ByteString
      getPatientIDBytes();

  /**
   * <code>.google.protobuf.Timestamp date = 3;</code>
   */
  boolean hasDate();
  /**
   * <code>.google.protobuf.Timestamp date = 3;</code>
   */
  com.google.protobuf.Timestamp getDate();
  /**
   * <code>.google.protobuf.Timestamp date = 3;</code>
   */
  com.google.protobuf.TimestampOrBuilder getDateOrBuilder();

  /**
   * <code>string prescriptionText = 4;</code>
   */
  java.lang.String getPrescriptionText();
  /**
   * <code>string prescriptionText = 4;</code>
   */
  com.google.protobuf.ByteString
      getPrescriptionTextBytes();
}
