// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PermissionService.proto

package grpc.Joanna.PermissionService;

public interface AccessInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AccessInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string doctorID = 1;</code>
   */
  java.lang.String getDoctorID();
  /**
   * <code>string doctorID = 1;</code>
   */
  com.google.protobuf.ByteString
      getDoctorIDBytes();

  /**
   * <code>string patientID = 2;</code>
   */
  java.lang.String getPatientID();
  /**
   * <code>string patientID = 2;</code>
   */
  com.google.protobuf.ByteString
      getPatientIDBytes();
}
