// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PermissionService.proto

package joanna.CA1.Smarthealth;

public interface AccessInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Smarthealth.AccessInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string doctorID = 1;</code>
   * @return The doctorID.
   */
  java.lang.String getDoctorID();
  /**
   * <code>string doctorID = 1;</code>
   * @return The bytes for doctorID.
   */
  com.google.protobuf.ByteString
      getDoctorIDBytes();

  /**
   * <code>string patientID = 2;</code>
   * @return The patientID.
   */
  java.lang.String getPatientID();
  /**
   * <code>string patientID = 2;</code>
   * @return The bytes for patientID.
   */
  com.google.protobuf.ByteString
      getPatientIDBytes();
}
