// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PermissionService.proto

package joanna.CA1.Smarthealth;

public interface AccessLogEntryOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Smarthealth.AccessLogEntry)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.google.protobuf.Timestamp date = 1;</code>
   * @return Whether the date field is set.
   */
  boolean hasDate();
  /**
   * <code>.google.protobuf.Timestamp date = 1;</code>
   * @return The date.
   */
  com.google.protobuf.Timestamp getDate();
  /**
   * <code>.google.protobuf.Timestamp date = 1;</code>
   */
  com.google.protobuf.TimestampOrBuilder getDateOrBuilder();

  /**
   * <code>string accessType = 2;</code>
   * @return The accessType.
   */
  java.lang.String getAccessType();
  /**
   * <code>string accessType = 2;</code>
   * @return The bytes for accessType.
   */
  com.google.protobuf.ByteString
      getAccessTypeBytes();

  /**
   * <code>string operationType = 3;</code>
   * @return The operationType.
   */
  java.lang.String getOperationType();
  /**
   * <code>string operationType = 3;</code>
   * @return The bytes for operationType.
   */
  com.google.protobuf.ByteString
      getOperationTypeBytes();
}
