// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PatientDataService.proto

package joanna.CA1.Smarthealth;

public final class PatientDataServiceImplBase {
  private PatientDataServiceImplBase() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Smarthealth_Prescription_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Smarthealth_Prescription_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Smarthealth_LabResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Smarthealth_LabResult_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Smarthealth_GetPrescriptionInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Smarthealth_GetPrescriptionInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Smarthealth_DoctorNote_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Smarthealth_DoctorNote_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030PatientDataService.proto\022\013Smarthealth\032" +
      "\037google/protobuf/timestamp.proto\032\014Shared" +
      ".proto\"w\n\014Prescription\022\020\n\010doctorID\030\001 \001(\t" +
      "\022\021\n\tpatientID\030\002 \001(\t\022(\n\004date\030\003 \001(\0132\032.goog" +
      "le.protobuf.Timestamp\022\030\n\020prescriptionTex" +
      "t\030\004 \001(\t\"\217\001\n\tLabResult\022\020\n\010doctorID\030\001 \001(\t\022" +
      "\021\n\tpatientID\030\002 \001(\t\022(\n\004date\030\003 \001(\0132\032.googl" +
      "e.protobuf.Timestamp\022\017\n\007labType\030\004 \001(\t\022\017\n" +
      "\007results\030\005 \001(\t\022\021\n\tdiagnosis\030\006 \001(\t\"(\n\023Get" +
      "PrescriptionInfo\022\021\n\tpatientID\030\001 \001(\t\"\226\001\n\n" +
      "DoctorNote\022\020\n\010doctorID\030\001 \001(\t\022\021\n\tpatientI" +
      "D\030\002 \001(\t\022(\n\004date\030\003 \001(\0132\032.google.protobuf." +
      "Timestamp\022\021\n\tdiagnosis\030\004 \001(\t\022\027\n\017recommen" +
      "dations\030\005 \001(\t\022\r\n\005notes\030\006 \001(\t2\313\002\n\022Patient" +
      "DataService\022J\n\017AddPrescription\022\031.Smarthe" +
      "alth.Prescription\032\032.Smarthealth.RequestR" +
      "esult\"\000\022S\n\020GetPrescriptions\022 .Smarthealt" +
      "h.GetPrescriptionInfo\032\031.Smarthealth.Pres" +
      "cription\"\0000\001\022I\n\rAddLabResults\022\026.Smarthea" +
      "lth.LabResult\032\032.Smarthealth.RequestResul" +
      "t\"\000(\0010\001\022I\n\016AddDoctorNotes\022\031.Smarthealth." +
      "Prescription\032\032.Smarthealth.RequestResult" +
      "\"\000B6\n\026joanna.CA1.SmarthealthB\032PatientDat" +
      "aServiceImplBaseP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
          joanna.CA1.Smarthealth.Shared.getDescriptor(),
        });
    internal_static_Smarthealth_Prescription_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Smarthealth_Prescription_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Smarthealth_Prescription_descriptor,
        new java.lang.String[] { "DoctorID", "PatientID", "Date", "PrescriptionText", });
    internal_static_Smarthealth_LabResult_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Smarthealth_LabResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Smarthealth_LabResult_descriptor,
        new java.lang.String[] { "DoctorID", "PatientID", "Date", "LabType", "Results", "Diagnosis", });
    internal_static_Smarthealth_GetPrescriptionInfo_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Smarthealth_GetPrescriptionInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Smarthealth_GetPrescriptionInfo_descriptor,
        new java.lang.String[] { "PatientID", });
    internal_static_Smarthealth_DoctorNote_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_Smarthealth_DoctorNote_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Smarthealth_DoctorNote_descriptor,
        new java.lang.String[] { "DoctorID", "PatientID", "Date", "Diagnosis", "Recommendations", "Notes", });
    com.google.protobuf.TimestampProto.getDescriptor();
    joanna.CA1.Smarthealth.Shared.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
