// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PermissionService.proto

package joanna.CA1.Smarthealth;

/**
 * <pre>
 * parameters needed to retriebe the access history of a patient
 * </pre>
 *
 * Protobuf type {@code Smarthealth.RequestLogHistoryInfo}
 */
public final class RequestLogHistoryInfo extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Smarthealth.RequestLogHistoryInfo)
    RequestLogHistoryInfoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use RequestLogHistoryInfo.newBuilder() to construct.
  private RequestLogHistoryInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private RequestLogHistoryInfo() {
    doctorID_ = "";
    patientID_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new RequestLogHistoryInfo();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private RequestLogHistoryInfo(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            doctorID_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            patientID_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return joanna.CA1.Smarthealth.PermissionServiceImplBase.internal_static_Smarthealth_RequestLogHistoryInfo_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return joanna.CA1.Smarthealth.PermissionServiceImplBase.internal_static_Smarthealth_RequestLogHistoryInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            joanna.CA1.Smarthealth.RequestLogHistoryInfo.class, joanna.CA1.Smarthealth.RequestLogHistoryInfo.Builder.class);
  }

  public static final int DOCTORID_FIELD_NUMBER = 1;
  private volatile java.lang.Object doctorID_;
  /**
   * <code>string doctorID = 1;</code>
   * @return The doctorID.
   */
  @java.lang.Override
  public java.lang.String getDoctorID() {
    java.lang.Object ref = doctorID_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      doctorID_ = s;
      return s;
    }
  }
  /**
   * <code>string doctorID = 1;</code>
   * @return The bytes for doctorID.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDoctorIDBytes() {
    java.lang.Object ref = doctorID_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      doctorID_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PATIENTID_FIELD_NUMBER = 2;
  private volatile java.lang.Object patientID_;
  /**
   * <code>string patientID = 2;</code>
   * @return The patientID.
   */
  @java.lang.Override
  public java.lang.String getPatientID() {
    java.lang.Object ref = patientID_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      patientID_ = s;
      return s;
    }
  }
  /**
   * <code>string patientID = 2;</code>
   * @return The bytes for patientID.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPatientIDBytes() {
    java.lang.Object ref = patientID_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      patientID_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(doctorID_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, doctorID_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(patientID_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, patientID_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(doctorID_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, doctorID_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(patientID_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, patientID_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof joanna.CA1.Smarthealth.RequestLogHistoryInfo)) {
      return super.equals(obj);
    }
    joanna.CA1.Smarthealth.RequestLogHistoryInfo other = (joanna.CA1.Smarthealth.RequestLogHistoryInfo) obj;

    if (!getDoctorID()
        .equals(other.getDoctorID())) return false;
    if (!getPatientID()
        .equals(other.getPatientID())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + DOCTORID_FIELD_NUMBER;
    hash = (53 * hash) + getDoctorID().hashCode();
    hash = (37 * hash) + PATIENTID_FIELD_NUMBER;
    hash = (53 * hash) + getPatientID().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static joanna.CA1.Smarthealth.RequestLogHistoryInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static joanna.CA1.Smarthealth.RequestLogHistoryInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static joanna.CA1.Smarthealth.RequestLogHistoryInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static joanna.CA1.Smarthealth.RequestLogHistoryInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static joanna.CA1.Smarthealth.RequestLogHistoryInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static joanna.CA1.Smarthealth.RequestLogHistoryInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static joanna.CA1.Smarthealth.RequestLogHistoryInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static joanna.CA1.Smarthealth.RequestLogHistoryInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static joanna.CA1.Smarthealth.RequestLogHistoryInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static joanna.CA1.Smarthealth.RequestLogHistoryInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static joanna.CA1.Smarthealth.RequestLogHistoryInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static joanna.CA1.Smarthealth.RequestLogHistoryInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(joanna.CA1.Smarthealth.RequestLogHistoryInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * parameters needed to retriebe the access history of a patient
   * </pre>
   *
   * Protobuf type {@code Smarthealth.RequestLogHistoryInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Smarthealth.RequestLogHistoryInfo)
      joanna.CA1.Smarthealth.RequestLogHistoryInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return joanna.CA1.Smarthealth.PermissionServiceImplBase.internal_static_Smarthealth_RequestLogHistoryInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return joanna.CA1.Smarthealth.PermissionServiceImplBase.internal_static_Smarthealth_RequestLogHistoryInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              joanna.CA1.Smarthealth.RequestLogHistoryInfo.class, joanna.CA1.Smarthealth.RequestLogHistoryInfo.Builder.class);
    }

    // Construct using joanna.CA1.Smarthealth.RequestLogHistoryInfo.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      doctorID_ = "";

      patientID_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return joanna.CA1.Smarthealth.PermissionServiceImplBase.internal_static_Smarthealth_RequestLogHistoryInfo_descriptor;
    }

    @java.lang.Override
    public joanna.CA1.Smarthealth.RequestLogHistoryInfo getDefaultInstanceForType() {
      return joanna.CA1.Smarthealth.RequestLogHistoryInfo.getDefaultInstance();
    }

    @java.lang.Override
    public joanna.CA1.Smarthealth.RequestLogHistoryInfo build() {
      joanna.CA1.Smarthealth.RequestLogHistoryInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public joanna.CA1.Smarthealth.RequestLogHistoryInfo buildPartial() {
      joanna.CA1.Smarthealth.RequestLogHistoryInfo result = new joanna.CA1.Smarthealth.RequestLogHistoryInfo(this);
      result.doctorID_ = doctorID_;
      result.patientID_ = patientID_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof joanna.CA1.Smarthealth.RequestLogHistoryInfo) {
        return mergeFrom((joanna.CA1.Smarthealth.RequestLogHistoryInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(joanna.CA1.Smarthealth.RequestLogHistoryInfo other) {
      if (other == joanna.CA1.Smarthealth.RequestLogHistoryInfo.getDefaultInstance()) return this;
      if (!other.getDoctorID().isEmpty()) {
        doctorID_ = other.doctorID_;
        onChanged();
      }
      if (!other.getPatientID().isEmpty()) {
        patientID_ = other.patientID_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      joanna.CA1.Smarthealth.RequestLogHistoryInfo parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (joanna.CA1.Smarthealth.RequestLogHistoryInfo) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object doctorID_ = "";
    /**
     * <code>string doctorID = 1;</code>
     * @return The doctorID.
     */
    public java.lang.String getDoctorID() {
      java.lang.Object ref = doctorID_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        doctorID_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string doctorID = 1;</code>
     * @return The bytes for doctorID.
     */
    public com.google.protobuf.ByteString
        getDoctorIDBytes() {
      java.lang.Object ref = doctorID_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        doctorID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string doctorID = 1;</code>
     * @param value The doctorID to set.
     * @return This builder for chaining.
     */
    public Builder setDoctorID(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      doctorID_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string doctorID = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearDoctorID() {
      
      doctorID_ = getDefaultInstance().getDoctorID();
      onChanged();
      return this;
    }
    /**
     * <code>string doctorID = 1;</code>
     * @param value The bytes for doctorID to set.
     * @return This builder for chaining.
     */
    public Builder setDoctorIDBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      doctorID_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object patientID_ = "";
    /**
     * <code>string patientID = 2;</code>
     * @return The patientID.
     */
    public java.lang.String getPatientID() {
      java.lang.Object ref = patientID_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        patientID_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string patientID = 2;</code>
     * @return The bytes for patientID.
     */
    public com.google.protobuf.ByteString
        getPatientIDBytes() {
      java.lang.Object ref = patientID_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        patientID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string patientID = 2;</code>
     * @param value The patientID to set.
     * @return This builder for chaining.
     */
    public Builder setPatientID(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      patientID_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string patientID = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearPatientID() {
      
      patientID_ = getDefaultInstance().getPatientID();
      onChanged();
      return this;
    }
    /**
     * <code>string patientID = 2;</code>
     * @param value The bytes for patientID to set.
     * @return This builder for chaining.
     */
    public Builder setPatientIDBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      patientID_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Smarthealth.RequestLogHistoryInfo)
  }

  // @@protoc_insertion_point(class_scope:Smarthealth.RequestLogHistoryInfo)
  private static final joanna.CA1.Smarthealth.RequestLogHistoryInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new joanna.CA1.Smarthealth.RequestLogHistoryInfo();
  }

  public static joanna.CA1.Smarthealth.RequestLogHistoryInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RequestLogHistoryInfo>
      PARSER = new com.google.protobuf.AbstractParser<RequestLogHistoryInfo>() {
    @java.lang.Override
    public RequestLogHistoryInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new RequestLogHistoryInfo(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<RequestLogHistoryInfo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RequestLogHistoryInfo> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public joanna.CA1.Smarthealth.RequestLogHistoryInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

