// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Shared.proto

package joanna.CA1.Smarthealth;

/**
 * <pre>
 * re-used status return message across multple RPC
 * </pre>
 *
 * Protobuf type {@code Smarthealth.RequestResult}
 */
public final class RequestResult extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Smarthealth.RequestResult)
    RequestResultOrBuilder {
private static final long serialVersionUID = 0L;
  // Use RequestResult.newBuilder() to construct.
  private RequestResult(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private RequestResult() {
    nonSuccessHint_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new RequestResult();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private RequestResult(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            success_ = input.readBool();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            nonSuccessHint_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return joanna.CA1.Smarthealth.Shared.internal_static_Smarthealth_RequestResult_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return joanna.CA1.Smarthealth.Shared.internal_static_Smarthealth_RequestResult_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            joanna.CA1.Smarthealth.RequestResult.class, joanna.CA1.Smarthealth.RequestResult.Builder.class);
  }

  public static final int SUCCESS_FIELD_NUMBER = 1;
  private boolean success_;
  /**
   * <code>bool success = 1;</code>
   * @return The success.
   */
  @java.lang.Override
  public boolean getSuccess() {
    return success_;
  }

  public static final int NONSUCCESSHINT_FIELD_NUMBER = 2;
  private volatile java.lang.Object nonSuccessHint_;
  /**
   * <pre>
   * if 'success' is false, then this field may contain additional information
   * </pre>
   *
   * <code>string nonSuccessHint = 2;</code>
   * @return The nonSuccessHint.
   */
  @java.lang.Override
  public java.lang.String getNonSuccessHint() {
    java.lang.Object ref = nonSuccessHint_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      nonSuccessHint_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * if 'success' is false, then this field may contain additional information
   * </pre>
   *
   * <code>string nonSuccessHint = 2;</code>
   * @return The bytes for nonSuccessHint.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNonSuccessHintBytes() {
    java.lang.Object ref = nonSuccessHint_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      nonSuccessHint_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (success_ != false) {
      output.writeBool(1, success_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(nonSuccessHint_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, nonSuccessHint_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (success_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, success_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(nonSuccessHint_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, nonSuccessHint_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof joanna.CA1.Smarthealth.RequestResult)) {
      return super.equals(obj);
    }
    joanna.CA1.Smarthealth.RequestResult other = (joanna.CA1.Smarthealth.RequestResult) obj;

    if (getSuccess()
        != other.getSuccess()) return false;
    if (!getNonSuccessHint()
        .equals(other.getNonSuccessHint())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SUCCESS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getSuccess());
    hash = (37 * hash) + NONSUCCESSHINT_FIELD_NUMBER;
    hash = (53 * hash) + getNonSuccessHint().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static joanna.CA1.Smarthealth.RequestResult parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static joanna.CA1.Smarthealth.RequestResult parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static joanna.CA1.Smarthealth.RequestResult parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static joanna.CA1.Smarthealth.RequestResult parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static joanna.CA1.Smarthealth.RequestResult parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static joanna.CA1.Smarthealth.RequestResult parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static joanna.CA1.Smarthealth.RequestResult parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static joanna.CA1.Smarthealth.RequestResult parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static joanna.CA1.Smarthealth.RequestResult parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static joanna.CA1.Smarthealth.RequestResult parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static joanna.CA1.Smarthealth.RequestResult parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static joanna.CA1.Smarthealth.RequestResult parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(joanna.CA1.Smarthealth.RequestResult prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * re-used status return message across multple RPC
   * </pre>
   *
   * Protobuf type {@code Smarthealth.RequestResult}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Smarthealth.RequestResult)
      joanna.CA1.Smarthealth.RequestResultOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return joanna.CA1.Smarthealth.Shared.internal_static_Smarthealth_RequestResult_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return joanna.CA1.Smarthealth.Shared.internal_static_Smarthealth_RequestResult_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              joanna.CA1.Smarthealth.RequestResult.class, joanna.CA1.Smarthealth.RequestResult.Builder.class);
    }

    // Construct using joanna.CA1.Smarthealth.RequestResult.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      success_ = false;

      nonSuccessHint_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return joanna.CA1.Smarthealth.Shared.internal_static_Smarthealth_RequestResult_descriptor;
    }

    @java.lang.Override
    public joanna.CA1.Smarthealth.RequestResult getDefaultInstanceForType() {
      return joanna.CA1.Smarthealth.RequestResult.getDefaultInstance();
    }

    @java.lang.Override
    public joanna.CA1.Smarthealth.RequestResult build() {
      joanna.CA1.Smarthealth.RequestResult result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public joanna.CA1.Smarthealth.RequestResult buildPartial() {
      joanna.CA1.Smarthealth.RequestResult result = new joanna.CA1.Smarthealth.RequestResult(this);
      result.success_ = success_;
      result.nonSuccessHint_ = nonSuccessHint_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof joanna.CA1.Smarthealth.RequestResult) {
        return mergeFrom((joanna.CA1.Smarthealth.RequestResult)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(joanna.CA1.Smarthealth.RequestResult other) {
      if (other == joanna.CA1.Smarthealth.RequestResult.getDefaultInstance()) return this;
      if (other.getSuccess() != false) {
        setSuccess(other.getSuccess());
      }
      if (!other.getNonSuccessHint().isEmpty()) {
        nonSuccessHint_ = other.nonSuccessHint_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      joanna.CA1.Smarthealth.RequestResult parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (joanna.CA1.Smarthealth.RequestResult) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private boolean success_ ;
    /**
     * <code>bool success = 1;</code>
     * @return The success.
     */
    @java.lang.Override
    public boolean getSuccess() {
      return success_;
    }
    /**
     * <code>bool success = 1;</code>
     * @param value The success to set.
     * @return This builder for chaining.
     */
    public Builder setSuccess(boolean value) {
      
      success_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool success = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearSuccess() {
      
      success_ = false;
      onChanged();
      return this;
    }

    private java.lang.Object nonSuccessHint_ = "";
    /**
     * <pre>
     * if 'success' is false, then this field may contain additional information
     * </pre>
     *
     * <code>string nonSuccessHint = 2;</code>
     * @return The nonSuccessHint.
     */
    public java.lang.String getNonSuccessHint() {
      java.lang.Object ref = nonSuccessHint_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nonSuccessHint_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * if 'success' is false, then this field may contain additional information
     * </pre>
     *
     * <code>string nonSuccessHint = 2;</code>
     * @return The bytes for nonSuccessHint.
     */
    public com.google.protobuf.ByteString
        getNonSuccessHintBytes() {
      java.lang.Object ref = nonSuccessHint_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nonSuccessHint_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * if 'success' is false, then this field may contain additional information
     * </pre>
     *
     * <code>string nonSuccessHint = 2;</code>
     * @param value The nonSuccessHint to set.
     * @return This builder for chaining.
     */
    public Builder setNonSuccessHint(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      nonSuccessHint_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * if 'success' is false, then this field may contain additional information
     * </pre>
     *
     * <code>string nonSuccessHint = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearNonSuccessHint() {
      
      nonSuccessHint_ = getDefaultInstance().getNonSuccessHint();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * if 'success' is false, then this field may contain additional information
     * </pre>
     *
     * <code>string nonSuccessHint = 2;</code>
     * @param value The bytes for nonSuccessHint to set.
     * @return This builder for chaining.
     */
    public Builder setNonSuccessHintBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      nonSuccessHint_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Smarthealth.RequestResult)
  }

  // @@protoc_insertion_point(class_scope:Smarthealth.RequestResult)
  private static final joanna.CA1.Smarthealth.RequestResult DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new joanna.CA1.Smarthealth.RequestResult();
  }

  public static joanna.CA1.Smarthealth.RequestResult getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RequestResult>
      PARSER = new com.google.protobuf.AbstractParser<RequestResult>() {
    @java.lang.Override
    public RequestResult parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new RequestResult(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<RequestResult> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RequestResult> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public joanna.CA1.Smarthealth.RequestResult getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

