// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Shared.proto

package joanna.CA1.Smarthealth;

public final class Shared {
  private Shared() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Smarthealth_RequestResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Smarthealth_RequestResult_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014Shared.proto\022\013Smarthealth\"8\n\rRequestRe" +
      "sult\022\017\n\007success\030\001 \001(\010\022\026\n\016nonSuccessHint\030" +
      "\002 \001(\tB\032\n\026joanna.CA1.SmarthealthP\001b\006proto" +
      "3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Smarthealth_RequestResult_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Smarthealth_RequestResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Smarthealth_RequestResult_descriptor,
        new java.lang.String[] { "Success", "NonSuccessHint", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
