// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SupportService.proto

package joanna.CA1.Smarthealth;

public final class SupportServiceImplBase {
  private SupportServiceImplBase() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Smarthealth_RequestChatInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Smarthealth_RequestChatInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Smarthealth_QueueUpforChatInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Smarthealth_QueueUpforChatInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Smarthealth_QueueStatusInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Smarthealth_QueueStatusInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Smarthealth_ChatMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Smarthealth_ChatMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024SupportService.proto\022\013Smarthealth\032\014Sha" +
      "red.proto\"s\n\017RequestChatInfo\022\016\n\006userID\030\001" +
      " \001(\t\022\017\n\007subject\030\002 \001(\t\022\023\n\013description\030\003 \001" +
      "(\t\022\023\n\013phoneNumber\030\004 \001(\t\022\025\n\rpreferredTime" +
      "\030\005 \001(\t\"5\n\022QueueUpforChatInfo\022\016\n\006userID\030\001" +
      " \001(\t\022\017\n\007subject\030\002 \001(\t\"6\n\017QueueStatusInfo" +
      "\022\016\n\006userID\030\001 \001(\t\022\023\n\013rankInQueue\030\002 \001(\005\".\n" +
      "\013ChatMessage\022\016\n\006userID\030\001 \001(\t\022\017\n\007message\030" +
      "\002 \001(\t2\202\002\n\016SupportService\022N\n\020RequestPhone" +
      "Call\022\034.Smarthealth.RequestChatInfo\032\032.Sma" +
      "rthealth.RequestResult\"\000\022S\n\016QueueUpforCh" +
      "at\022\037.Smarthealth.QueueUpforChatInfo\032\034.Sm" +
      "arthealth.QueueStatusInfo\"\0000\001\022K\n\017Interac" +
      "tiveChat\022\030.Smarthealth.ChatMessage\032\030.Sma" +
      "rthealth.ChatMessage\"\000(\0010\001B2\n\026joanna.CA1" +
      ".SmarthealthB\026SupportServiceImplBaseP\001b\006" +
      "proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          joanna.CA1.Smarthealth.Shared.getDescriptor(),
        });
    internal_static_Smarthealth_RequestChatInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Smarthealth_RequestChatInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Smarthealth_RequestChatInfo_descriptor,
        new java.lang.String[] { "UserID", "Subject", "Description", "PhoneNumber", "PreferredTime", });
    internal_static_Smarthealth_QueueUpforChatInfo_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Smarthealth_QueueUpforChatInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Smarthealth_QueueUpforChatInfo_descriptor,
        new java.lang.String[] { "UserID", "Subject", });
    internal_static_Smarthealth_QueueStatusInfo_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Smarthealth_QueueStatusInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Smarthealth_QueueStatusInfo_descriptor,
        new java.lang.String[] { "UserID", "RankInQueue", });
    internal_static_Smarthealth_ChatMessage_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_Smarthealth_ChatMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Smarthealth_ChatMessage_descriptor,
        new java.lang.String[] { "UserID", "Message", });
    joanna.CA1.Smarthealth.Shared.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
