# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PatientDataService.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
import Shared_pb2 as Shared__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18PatientDataService.proto\x12\x0bSmarthealth\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x0cShared.proto\"w\n\x0cPrescription\x12\x10\n\x08\x64octorID\x18\x01 \x01(\t\x12\x11\n\tpatientID\x18\x02 \x01(\t\x12(\n\x04\x64\x61te\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x18\n\x10prescriptionText\x18\x04 \x01(\t\"\x8f\x01\n\tLabResult\x12\x10\n\x08\x64octorID\x18\x01 \x01(\t\x12\x11\n\tpatientID\x18\x02 \x01(\t\x12(\n\x04\x64\x61te\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0f\n\x07labType\x18\x04 \x01(\t\x12\x0f\n\x07results\x18\x05 \x01(\t\x12\x11\n\tdiagnosis\x18\x06 \x01(\t\"(\n\x13GetPrescriptionInfo\x12\x11\n\tpatientID\x18\x01 \x01(\t\"\x96\x01\n\nDoctorNote\x12\x10\n\x08\x64octorID\x18\x01 \x01(\t\x12\x11\n\tpatientID\x18\x02 \x01(\t\x12(\n\x04\x64\x61te\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x11\n\tdiagnosis\x18\x04 \x01(\t\x12\x17\n\x0frecommendations\x18\x05 \x01(\t\x12\r\n\x05notes\x18\x06 \x01(\t2\xcb\x02\n\x12PatientDataService\x12J\n\x0f\x41\x64\x64Prescription\x12\x19.Smarthealth.Prescription\x1a\x1a.Smarthealth.RequestResult\"\x00\x12S\n\x10GetPrescriptions\x12 .Smarthealth.GetPrescriptionInfo\x1a\x19.Smarthealth.Prescription\"\x00\x30\x01\x12I\n\rAddLabResults\x12\x16.Smarthealth.LabResult\x1a\x1a.Smarthealth.RequestResult\"\x00(\x01\x30\x01\x12I\n\x0e\x41\x64\x64\x44octorNotes\x12\x19.Smarthealth.Prescription\x1a\x1a.Smarthealth.RequestResult\"\x00\x42\x36\n\x16joanna.CA1.SmarthealthB\x1aPatientDataServiceImplBaseP\x01\x62\x06proto3')



_PRESCRIPTION = DESCRIPTOR.message_types_by_name['Prescription']
_LABRESULT = DESCRIPTOR.message_types_by_name['LabResult']
_GETPRESCRIPTIONINFO = DESCRIPTOR.message_types_by_name['GetPrescriptionInfo']
_DOCTORNOTE = DESCRIPTOR.message_types_by_name['DoctorNote']
Prescription = _reflection.GeneratedProtocolMessageType('Prescription', (_message.Message,), {
  'DESCRIPTOR' : _PRESCRIPTION,
  '__module__' : 'PatientDataService_pb2'
  # @@protoc_insertion_point(class_scope:Smarthealth.Prescription)
  })
_sym_db.RegisterMessage(Prescription)

LabResult = _reflection.GeneratedProtocolMessageType('LabResult', (_message.Message,), {
  'DESCRIPTOR' : _LABRESULT,
  '__module__' : 'PatientDataService_pb2'
  # @@protoc_insertion_point(class_scope:Smarthealth.LabResult)
  })
_sym_db.RegisterMessage(LabResult)

GetPrescriptionInfo = _reflection.GeneratedProtocolMessageType('GetPrescriptionInfo', (_message.Message,), {
  'DESCRIPTOR' : _GETPRESCRIPTIONINFO,
  '__module__' : 'PatientDataService_pb2'
  # @@protoc_insertion_point(class_scope:Smarthealth.GetPrescriptionInfo)
  })
_sym_db.RegisterMessage(GetPrescriptionInfo)

DoctorNote = _reflection.GeneratedProtocolMessageType('DoctorNote', (_message.Message,), {
  'DESCRIPTOR' : _DOCTORNOTE,
  '__module__' : 'PatientDataService_pb2'
  # @@protoc_insertion_point(class_scope:Smarthealth.DoctorNote)
  })
_sym_db.RegisterMessage(DoctorNote)

_PATIENTDATASERVICE = DESCRIPTOR.services_by_name['PatientDataService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\026joanna.CA1.SmarthealthB\032PatientDataServiceImplBaseP\001'
  _PRESCRIPTION._serialized_start=88
  _PRESCRIPTION._serialized_end=207
  _LABRESULT._serialized_start=210
  _LABRESULT._serialized_end=353
  _GETPRESCRIPTIONINFO._serialized_start=355
  _GETPRESCRIPTIONINFO._serialized_end=395
  _DOCTORNOTE._serialized_start=398
  _DOCTORNOTE._serialized_end=548
  _PATIENTDATASERVICE._serialized_start=551
  _PATIENTDATASERVICE._serialized_end=882
# @@protoc_insertion_point(module_scope)
