# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PermissionService.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
import Shared_pb2 as Shared__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17PermissionService.proto\x12\x0bSmarthealth\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x0cShared.proto\"1\n\nAccessInfo\x12\x10\n\x08\x64octorID\x18\x01 \x01(\t\x12\x11\n\tpatientID\x18\x02 \x01(\t\"<\n\x15RequestLogHistoryInfo\x12\x10\n\x08\x64octorID\x18\x01 \x01(\t\x12\x11\n\tpatientID\x18\x02 \x01(\t\"e\n\x0e\x41\x63\x63\x65ssLogEntry\x12(\n\x04\x64\x61te\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x12\n\naccessType\x18\x02 \x01(\t\x12\x15\n\roperationType\x18\x03 \x01(\t2\xff\x01\n\x11PermissionService\x12G\n\x0eGiveDataAccess\x12\x17.Smarthealth.AccessInfo\x1a\x1a.Smarthealth.RequestResult\"\x00\x12H\n\x0fRemoveDataAcess\x12\x17.Smarthealth.AccessInfo\x1a\x1a.Smarthealth.RequestResult\"\x00\x12W\n\x10GetAccessHistory\x12\".Smarthealth.RequestLogHistoryInfo\x1a\x1b.Smarthealth.AccessLogEntry\"\x00\x30\x01\x42\x35\n\x16joanna.CA1.SmarthealthB\x19PermissionServiceImplBaseP\x01\x62\x06proto3')



_ACCESSINFO = DESCRIPTOR.message_types_by_name['AccessInfo']
_REQUESTLOGHISTORYINFO = DESCRIPTOR.message_types_by_name['RequestLogHistoryInfo']
_ACCESSLOGENTRY = DESCRIPTOR.message_types_by_name['AccessLogEntry']
AccessInfo = _reflection.GeneratedProtocolMessageType('AccessInfo', (_message.Message,), {
  'DESCRIPTOR' : _ACCESSINFO,
  '__module__' : 'PermissionService_pb2'
  # @@protoc_insertion_point(class_scope:Smarthealth.AccessInfo)
  })
_sym_db.RegisterMessage(AccessInfo)

RequestLogHistoryInfo = _reflection.GeneratedProtocolMessageType('RequestLogHistoryInfo', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTLOGHISTORYINFO,
  '__module__' : 'PermissionService_pb2'
  # @@protoc_insertion_point(class_scope:Smarthealth.RequestLogHistoryInfo)
  })
_sym_db.RegisterMessage(RequestLogHistoryInfo)

AccessLogEntry = _reflection.GeneratedProtocolMessageType('AccessLogEntry', (_message.Message,), {
  'DESCRIPTOR' : _ACCESSLOGENTRY,
  '__module__' : 'PermissionService_pb2'
  # @@protoc_insertion_point(class_scope:Smarthealth.AccessLogEntry)
  })
_sym_db.RegisterMessage(AccessLogEntry)

_PERMISSIONSERVICE = DESCRIPTOR.services_by_name['PermissionService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\026joanna.CA1.SmarthealthB\031PermissionServiceImplBaseP\001'
  _ACCESSINFO._serialized_start=87
  _ACCESSINFO._serialized_end=136
  _REQUESTLOGHISTORYINFO._serialized_start=138
  _REQUESTLOGHISTORYINFO._serialized_end=198
  _ACCESSLOGENTRY._serialized_start=200
  _ACCESSLOGENTRY._serialized_end=301
  _PERMISSIONSERVICE._serialized_start=304
  _PERMISSIONSERVICE._serialized_end=559
# @@protoc_insertion_point(module_scope)
