// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SupportService.proto

package grpc.Joanna.SupportService;

public interface ChatMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ChatMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string userID = 1;</code>
   */
  java.lang.String getUserID();
  /**
   * <code>string userID = 1;</code>
   */
  com.google.protobuf.ByteString
      getUserIDBytes();

  /**
   * <code>string message = 2;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
