// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SupportService.proto

package grpc.Joanna.SupportService;

public interface QueueStatusInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:QueueStatusInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string userID = 1;</code>
   */
  java.lang.String getUserID();
  /**
   * <code>string userID = 1;</code>
   */
  com.google.protobuf.ByteString
      getUserIDBytes();

  /**
   * <code>int32 rankInQueue = 2;</code>
   */
  int getRankInQueue();
}
