// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SupportService.proto

package grpc.Joanna.SupportService;

public interface QueueUpforChatInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:QueueUpforChatInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string userID = 1;</code>
   */
  java.lang.String getUserID();
  /**
   * <code>string userID = 1;</code>
   */
  com.google.protobuf.ByteString
      getUserIDBytes();

  /**
   * <code>string subject = 2;</code>
   */
  java.lang.String getSubject();
  /**
   * <code>string subject = 2;</code>
   */
  com.google.protobuf.ByteString
      getSubjectBytes();
}
