// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SupportService.proto

package grpc.Joanna.SupportService;

public interface RequestResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RequestResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool success = 1;</code>
   */
  boolean getSuccess();

  /**
   * <pre>
   * if 'success' is false, then this field may contain additional information
   * </pre>
   *
   * <code>string nonSuccessHint = 2;</code>
   */
  java.lang.String getNonSuccessHint();
  /**
   * <pre>
   * if 'success' is false, then this field may contain additional information
   * </pre>
   *
   * <code>string nonSuccessHint = 2;</code>
   */
  com.google.protobuf.ByteString
      getNonSuccessHintBytes();
}
