// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SupportService.proto

package grpc.Joanna.SupportService;

public interface RequestChatInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RequestChatInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * int?
   * </pre>
   *
   * <code>string userID = 1;</code>
   */
  java.lang.String getUserID();
  /**
   * <pre>
   * int?
   * </pre>
   *
   * <code>string userID = 1;</code>
   */
  com.google.protobuf.ByteString
      getUserIDBytes();

  /**
   * <code>string subject = 2;</code>
   */
  java.lang.String getSubject();
  /**
   * <code>string subject = 2;</code>
   */
  com.google.protobuf.ByteString
      getSubjectBytes();

  /**
   * <code>string description = 3;</code>
   */
  java.lang.String getDescription();
  /**
   * <code>string description = 3;</code>
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();

  /**
   * <pre>
   * to change the type
   * </pre>
   *
   * <code>string phoneNumber = 4;</code>
   */
  java.lang.String getPhoneNumber();
  /**
   * <pre>
   * to change the type
   * </pre>
   *
   * <code>string phoneNumber = 4;</code>
   */
  com.google.protobuf.ByteString
      getPhoneNumberBytes();

  /**
   * <pre>
   *change the type
   * </pre>
   *
   * <code>string preferredTime = 5;</code>
   */
  java.lang.String getPreferredTime();
  /**
   * <pre>
   *change the type
   * </pre>
   *
   * <code>string preferredTime = 5;</code>
   */
  com.google.protobuf.ByteString
      getPreferredTimeBytes();
}
