// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SupportService.proto

package grpc.Joanna.SupportService;

public final class SupportServiceImpl {
  private SupportServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RequestChatInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RequestChatInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_QueueUpforChatInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_QueueUpforChatInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_QueueStatusInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_QueueStatusInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ChatMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ChatMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RequestResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RequestResult_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024SupportService.proto\"s\n\017RequestChatInf" +
      "o\022\016\n\006userID\030\001 \001(\t\022\017\n\007subject\030\002 \001(\t\022\023\n\013de" +
      "scription\030\003 \001(\t\022\023\n\013phoneNumber\030\004 \001(\t\022\025\n\r" +
      "preferredTime\030\005 \001(\t\"5\n\022QueueUpforChatInf" +
      "o\022\016\n\006userID\030\001 \001(\t\022\017\n\007subject\030\002 \001(\t\"6\n\017Qu" +
      "eueStatusInfo\022\016\n\006userID\030\001 \001(\t\022\023\n\013rankInQ" +
      "ueue\030\002 \001(\005\".\n\013ChatMessage\022\016\n\006userID\030\001 \001(" +
      "\t\022\017\n\007message\030\002 \001(\t\"8\n\rRequestResult\022\017\n\007s" +
      "uccess\030\001 \001(\010\022\026\n\016nonSuccessHint\030\002 \001(\t2\272\001\n" +
      "\016SupportService\0226\n\020RequestPhoneCall\022\020.Re" +
      "questChatInfo\032\016.RequestResult\"\000\022;\n\016Queue" +
      "UpforChat\022\023.QueueUpforChatInfo\032\020.QueueSt" +
      "atusInfo\"\0000\001\0223\n\017InteractiveChat\022\014.ChatMe" +
      "ssage\032\014.ChatMessage\"\000(\0010\001B2\n\032grpc.Joanna" +
      ".SupportServiceB\022SupportServiceImplP\001b\006p" +
      "roto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_RequestChatInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_RequestChatInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RequestChatInfo_descriptor,
        new java.lang.String[] { "UserID", "Subject", "Description", "PhoneNumber", "PreferredTime", });
    internal_static_QueueUpforChatInfo_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_QueueUpforChatInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_QueueUpforChatInfo_descriptor,
        new java.lang.String[] { "UserID", "Subject", });
    internal_static_QueueStatusInfo_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_QueueStatusInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_QueueStatusInfo_descriptor,
        new java.lang.String[] { "UserID", "RankInQueue", });
    internal_static_ChatMessage_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_ChatMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ChatMessage_descriptor,
        new java.lang.String[] { "UserID", "Message", });
    internal_static_RequestResult_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_RequestResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RequestResult_descriptor,
        new java.lang.String[] { "Success", "NonSuccessHint", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
